<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ecl</string>
	</array>
	<key>name</key>
	<string>ECL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.epsilon.eol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(match|auto|do|compare|guard|pre|post|with|extends|rule|abstract)\b</string>
			<key>name</key>
			<string>keyword.control.ecl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(matchTrace|autoCompare|matchInfo)\b</string>
			<key>name</key>
			<string>constant.language.ecl</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.epsilon.ecl</string>
	<key>uuid</key>
	<string>28DCE4DD-F5E1-4ED3-8847-64DA6B1F9169</string>
</dict>
</plist>