<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>eol</string>
	</array>
	<key>name</key>
	<string>EOL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.eol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.line.double-slash.eol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@.*$</string>
			<key>name</key>
			<string>comment.line.annotation</string>
		</dict>		
		<!--dict>
			<key>match</key>
			<string>[!&lt;&gt;:]?=|&lt;&gt;|&lt;|&gt;|\+|(?&lt;!\.)\*|-|(?&lt;!^)/|@@|\|\|</string>
			<key>name</key>
			<string>keyword.operator.eol</string>
		</dict-->
		<dict>
			<key>match</key>
			<string>\b(true|false|self|loopCount|hasMore)\b</string>
			<key>name</key>
			<string>constant.language.eol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+(\.\d+)?\b</string>
			<key>name</key>
			<string>constant.numeric.eol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(import|driver|alias|if|switch|case|default|operation|function|new|else|for|var|return|async|break|breakAll|and|or|not|xor|implies|ext|in|continue|while|throw|delete|transaction|abort|model|group|as)\b</string>
			<key>name</key>
			<string>keyword.control.eol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.eol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.eol</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>end</key>
			<string>`</string>
			<key>name</key>
			<string>meta.other.eol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(String|Boolean|Integer|Real|Any|Map|Collection|Bag|Sequence|Set|OrderedSet|Native|List|Tuple|ConcurrentSet|ConcurrentBag|ConcurrentMap|EolSelf|EolSelfContentType|EolSelfExpressionType|EolSelfCollectionType)\b</string>
			<key>name</key>
			<string>storage.type.eol</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.epsilon.eol</string>
	<key>uuid</key>
	<string>28DCE4DD-F5E1-4ED3-8847-64DA6B1F9164</string>
</dict>
</plist>