on:
  push:
    branches:
  pull_request:
    branches:
      - main

name: Build Extension
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: "npm"
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven
      - name: Build the Language Server
        run: cd language-server && mvn --batch-mode --update-snapshots package
      - name: Install Node dependencies
        run: npm ci
      - name: Build the extension
        run: npm run compile
      - name: Package the extension
        run: npm install -g @vscode/vsce && vsce package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: built-extension
          path: "*.vsix"
